# Generated by Django 2.1.7 on 2019-04-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bookId', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=32)),
                ('author', models.CharField(max_length=64)),
                ('intro', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
    ]
